class TempList:
    list_comments = [{'data_com': 'Jun 17, 2023', 'time_comm': '12:22 pm', 'author_comm': 'Staking Epoch',
                      'text_comm': 'Start of a new staking session 6701'},
                     {'data_com': 'Jun 17, 2023', 'time_comm': '12:55 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jun 17, 2023', 'time_comm': '6:36 pm', 'author_comm': 'Staking Era',
                      'text_comm': 'Start of a new staking era 1111'},
                     {'data_com': 'Jun 19, 2023', 'time_comm': '12:51 am', 'author_comm': 'Start New Council Election',
                      'text_comm': 'Election of new council candidates period 158'},
                     {'data_com': 'Jun 19, 2023', 'time_comm': '11:29 am', 'author_comm': 'Council Motion',
                      'text_comm': 'Council Motion 0x852dee77...'},
                     {'data_com': 'Jun 22, 2023', 'time_comm': '7:45 pm', 'author_comm': 'Council Motion',
                      'text_comm': 'Council Motion 0x59ad6aed...'},
                     {'data_com': 'Jun 26, 2023', 'time_comm': '12:51 am',
                      'author_comm': 'Start Referendum Voting Period',
                      'text_comm': 'Start of next referendum voting period 39'},
                     {'data_com': 'Jun 29, 2023', 'time_comm': '3:35 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 1, 2023', 'time_comm': '5:52 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute named scheduled task 0x9dc85167...'},
                     {'data_com': 'Jul 4, 2023', 'time_comm': '12:51 am', 'author_comm': 'Start Spend Period',
                      'text_comm': 'Start of next spend period 46'},
                     {'data_com': 'Jul 12, 2023', 'time_comm': '8:28 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 12, 2023', 'time_comm': '7:02 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '9:46 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '8:51 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '9:56 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '10:12 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 14, 2023', 'time_comm': '1:34 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 14, 2023', 'time_comm': '5:03 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 14, 2023', 'time_comm': '6:51 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Aug 1, 2023', 'time_comm': '12:51 am', 'author_comm': 'Start Parachain Lease Period',
                      'text_comm': 'Start of the next parachain lease period 13'},
                     {'data_com': 'Aug 1, 2023', 'time_comm': '12:52 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute named scheduled task 0x9a6e9257...'},
                     {'data_com': 'Oct 24, 2023', 'time_comm': '12:52 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute named scheduled task 0x21fc0d6c...'}]

    link_posts = [{'name_them': 'Small Spender', 'links': [
            {'link': 'https://polkadot.polkassembly.io/post/1812', 'id': '7',
             'name_post': 'Ledger Apps Maintenance Proposal (Polkadot, Kusama, Statemine, Statemint)'},
            {'link': 'https://polkadot.polkassembly.io/referenda/2', 'id': '2',
             'name_post': 'ParaSpell XCM SDK Maintenance funding for 5months - Polkadot Treasury Proposal'},
            {'link': 'https://polkadot.polkassembly.io/referenda/1', 'id': '1',
             'name_post': 'OpenCommunity Governance'}]}, {'name_them': 'Discussions', 'links': [
        {'link': 'https://polkadot.polkassembly.io/post/1819', 'id': '1819',
         'name_post': '[Proposal] Risk assessment for enterprise engagement with Polkadot: a request fo...'},
        {'link': 'https://polkadot.polkassembly.io/post/1815', 'id': '1815',
         'name_post': "Polkassembly's Registrar Application"},
        {'link': 'https://polkadot.polkassembly.io/post/1814', 'id': '1814',
         'name_post': 'ParaSpell XCM SDK Maintenance funding for 5months - Polkadot Treasury Proposal'},
        {'link': 'https://polkadot.polkassembly.io/post/1813', 'id': '1813',
         'name_post': 'Saturn Gateway - A Multichain Multisig Application for the Polkadot Ecosystem'},
        {'link': 'https://polkadot.polkassembly.io/post/1812', 'id': '1812',
         'name_post': 'Ledger Apps Maintenance Proposal (Polkadot, Kusama, Statemine, Statemint)'}]},
                  {'name_them': 'Root',
                   'links': [{
                       'link': 'https://polkadot.polkassembly.io/referenda/9',
                       'id': '9',
                       'name_post': 'Fix HostConfiguration'}]},
                  {'name_them': 'Whitelisted Caller', 'links': [
                      {'link': 'https://polkadot.polkassembly.io/referenda/3', 'id': '3',
                       'name_post': 'dispatch_whitelisted_call_with_preimage'}]},
                  {'name_them': 'Small Tipper', 'links': [
                      {'link': 'https://polkadot.polkassembly.io/referenda/0', 'id': '0',
                       'name_post': '[Reject] Supposed to be Hello World'}]},
                  {'name_them': 'Medium Spender', 'links': [
                      {'link': 'https://polkadot.polkassembly.io/referenda/6', 'id': '6',
                       'name_post': 'Saturn Gateway - A Multichain Multisig Application for the Polkadot Ecosystem'},
                      {'link': 'https://polkadot.polkassembly.io/referenda/5', 'id': '5',
                       'name_post': 'KILT Decentralized Identity Provider (DIP) - Polkadot Medium Spender Proposal'},
                      {'link': 'https://polkadot.polkassembly.io/referenda/4', 'id': '4',
                       'name_post': 'PolkaWorld Ops and Maintenance proposal：2023.6 - 2023.8'}]},
                  {'name_them': 'Big Spender',
                   'links': [{'link': 'https://polkadot.polkassembly.io/referenda/8', 'id': '8',
                              'name_post': 'Nova Wallet 4th Proposal: Multistaking dashboard, Staking Nomination Pools, Wall...'}]}]
