class TempList:
    list_comments = [{'data_com': 'Jun 17, 2023', 'time_comm': '12:22 pm', 'author_comm': 'Staking Epoch',
                      'text_comm': 'Start of a new staking session 6701'},
                     {'data_com': 'Jun 17, 2023', 'time_comm': '12:55 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jun 17, 2023', 'time_comm': '6:36 pm', 'author_comm': 'Staking Era',
                      'text_comm': 'Start of a new staking era 1111'},
                     {'data_com': 'Jun 19, 2023', 'time_comm': '12:51 am', 'author_comm': 'Start New Council Election',
                      'text_comm': 'Election of new council candidates period 158'},
                     {'data_com': 'Jun 19, 2023', 'time_comm': '11:29 am', 'author_comm': 'Council Motion',
                      'text_comm': 'Council Motion 0x852dee77...'},
                     {'data_com': 'Jun 22, 2023', 'time_comm': '7:45 pm', 'author_comm': 'Council Motion',
                      'text_comm': 'Council Motion 0x59ad6aed...'},
                     {'data_com': 'Jun 26, 2023', 'time_comm': '12:51 am',
                      'author_comm': 'Start Referendum Voting Period',
                      'text_comm': 'Start of next referendum voting period 39'},
                     {'data_com': 'Jun 29, 2023', 'time_comm': '3:35 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 1, 2023', 'time_comm': '5:52 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute named scheduled task 0x9dc85167...'},
                     {'data_com': 'Jul 4, 2023', 'time_comm': '12:51 am', 'author_comm': 'Start Spend Period',
                      'text_comm': 'Start of next spend period 46'},
                     {'data_com': 'Jul 12, 2023', 'time_comm': '8:28 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 12, 2023', 'time_comm': '7:02 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '9:46 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '8:51 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '9:56 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 13, 2023', 'time_comm': '10:12 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 14, 2023', 'time_comm': '1:34 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 14, 2023', 'time_comm': '5:03 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Jul 14, 2023', 'time_comm': '6:51 pm', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute anonymous scheduled task'},
                     {'data_com': 'Aug 1, 2023', 'time_comm': '12:51 am', 'author_comm': 'Start Parachain Lease Period',
                      'text_comm': 'Start of the next parachain lease period 13'},
                     {'data_com': 'Aug 1, 2023', 'time_comm': '12:52 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute named scheduled task 0x9a6e9257...'},
                     {'data_com': 'Oct 24, 2023', 'time_comm': '12:52 am', 'author_comm': 'Scheduled Task',
                      'text_comm': 'Execute named scheduled task 0x21fc0d6c...'}]

    link_posts = [{'name_them': 'Small Spender', 'links': [
        {'link': 'https://polkadot.polkassembly.io/post/1812', 'id': '7',
         'name_post': 'Ledger Apps Maintenance Proposal (Polkadot, Kusama, Statemine, Statemint)'},
        {'link': 'https://polkadot.polkassembly.io/referenda/2', 'id': '2',
         'name_post': 'ParaSpell XCM SDK Maintenance funding for 5months - Polkadot Treasury Proposal'},
        {'link': 'https://polkadot.polkassembly.io/referenda/1', 'id': '1',
         'name_post': 'OpenCommunity Governance'}]}, {'name_them': 'Discussions', 'links': [
        {'link': 'https://polkadot.polkassembly.io/post/1819', 'id': '1819',
         'name_post': '[Proposal] Risk assessment for enterprise engagement with Polkadot: a request fo...'},
        {'link': 'https://polkadot.polkassembly.io/post/1815', 'id': '1815',
         'name_post': "Polkassembly's Registrar Application"},
        {'link': 'https://polkadot.polkassembly.io/post/1814', 'id': '1814',
         'name_post': 'ParaSpell XCM SDK Maintenance funding for 5months - Polkadot Treasury Proposal'},
        {'link': 'https://polkadot.polkassembly.io/post/1813', 'id': '1813',
         'name_post': 'Saturn Gateway - A Multichain Multisig Application for the Polkadot Ecosystem'},
        {'link': 'https://polkadot.polkassembly.io/post/1812', 'id': '1812',
         'name_post': 'Ledger Apps Maintenance Proposal (Polkadot, Kusama, Statemine, Statemint)'}]},
                  {'name_them': 'Root',
                   'links': [{
                       'link': 'https://polkadot.polkassembly.io/referenda/9',
                       'id': '9',
                       'name_post': 'Fix HostConfiguration'}]},
                  {'name_them': 'Whitelisted Caller', 'links': [
                      {'link': 'https://polkadot.polkassembly.io/referenda/3', 'id': '3',
                       'name_post': 'dispatch_whitelisted_call_with_preimage'}]},
                  {'name_them': 'Small Tipper', 'links': [
                      {'link': 'https://polkadot.polkassembly.io/referenda/0', 'id': '0',
                       'name_post': '[Reject] Supposed to be Hello World'}]},
                  {'name_them': 'Medium Spender', 'links': [
                      {'link': 'https://polkadot.polkassembly.io/referenda/6', 'id': '6',
                       'name_post': 'Saturn Gateway - A Multichain Multisig Application for the Polkadot Ecosystem'},
                      {'link': 'https://polkadot.polkassembly.io/referenda/5', 'id': '5',
                       'name_post': 'KILT Decentralized Identity Provider (DIP) - Polkadot Medium Spender Proposal'},
                      {'link': 'https://polkadot.polkassembly.io/referenda/4', 'id': '4',
                       'name_post': 'PolkaWorld Ops and Maintenance proposal：2023.6 - 2023.8'}]},
                  {'name_them': 'Big Spender',
                   'links': [{'link': 'https://polkadot.polkassembly.io/referenda/8', 'id': '8',
                              'name_post': 'Nova Wallet 4th Proposal: Multistaking dashboard, Staking Nomination Pools, Wall...'}]}]

    good_ower = [{'name_them': 'Discussions', 'links': [
        {'link': 'https://polkadot.polkassembly.io/post/1819', 'id': '1819',
         'name_post': '[Proposal] Risk assessment for enterprise engagement with Polkadot: a request fo...',
         'date': 'a day ago', 'data': {'name_author': 'DeloitteNL_Web3', 'status': 'enterprise', 'model': 'Treasury',
                                       'date_edit': 'a day ago',
                                       'post_text': "Deloitte intends to explore barriers, requirements and conditions to enhance enterprise engagements with Polkadot Network.\nA first project executes a case study for enterprise engagement with Polkadot Network through Polkadot Network's treasury spending process. This project will result in the creation of a case study report with an extensive risk inventory for enterprise-level organizations to engage with Polkadot Network. This deliverable will in turn contribute to Polkadot Network's enterprise readiness and its ability to collaborate with enterprise-level organizations and prepare for follow-up projects which aim to provide an enterprise blueprint for managed risk of Polkadot Network and it’s enterprise engagement.\nThe benefit for this project is not only to give the Polkadot community insight, but even more interesting, gives access to a broader audience struggling with the questions of how to interact with a decentralized organization like the Polkadot Network. From our experience, it is not obvious nor easy for highly regulated enterprises like Deloitte to be able to do this. By not only theoretically writing about these challenges but “practise what we preach '', we wish to show the world what happens in this process and how we overcome challenges. This way we want to help bridge the gap that exists between enterprise-level organizations and decentralized ecosystems like Polkadot Network.\nLink to proposal: https://bbosch.visualstudio.com/_git/Polkadot?path=/Deloitte%20Polkadot%20Treasury%20Project%20Proposal%20vFinalDraft.docx (copy and paste link in address bar if direct link does not work)",
                                       'like_post': '2', 'dislike_post': '2', 'decision': '0%', 'confirmation': '0%',
                                       'aye': '0%', 'nay': '0%', 'ayes': '0', 'nays': '0', 'support': '0',
                                       'issuance': '0', 'comment': [
                {'name_comment': 'OLIVER ⚡\nggwpez', 'time_comment': 'a day ago', 'text_comment': '@Oliver Thanks!',
                 'like': '1', 'dislike': '0'}, {'name_comment': '15tH...QbMt', 'time_comment': '6 hours ago',
                                                'text_comment': 'I agree with Oliver this is an area that could possibly be very beneficial for broader adoption of Polkadot, but in order for the community to understand it better and make a well informed decision we need to have a well structured proposal with all the necessary credentials. Such company as Deloitte has to understand that better then most.',
                                                'like': '0', 'dislike': '0'}]}}]}, {'name_them': 'Root', 'links': [
        {'link': 'https://polkadot.polkassembly.io/referenda/9', 'id': '9', 'name_post': 'Fix HostConfiguration',
         'date': 'a day ago', 'data': {'name_author': 'OLIVER ⚡\nggwpez', 'status': 'Deciding', 'model': 'Democracy',
                                       'date_edit': 'a day ago',
                                       'post_text': '(Same as on Kusama https://kusama.polkassembly.io/referenda/173)\nFix HostConfiguration (maxCodeSize to 3 MiB)\nThe current Polkadot HostConfiguration does not fulfill all assumptions about its consistency. This proposal aims at correcting that by modifying the on-chain config.\nProblem\nThe HostConfiguration::consistency_check function asserts that the on-chain max_code_size is never larger than MAX_CODE_SIZE. This is violated on Polkadot since the concrete max_code_size on-chain is 10 MiB and MAX_CODE_SIZE is only 3 MiB.\nYou can verify this by querying PolkadotJS:\nlet config = await api.query.configuration.activeConfig();\nconsole.log(config.maxCodeSize / (1024*1024), "MiB");\n// Prints 10 MiB\nIt is neccecary to correct this since otherwise the consistency_check will stay a No-OP with the assumption: "You cannot break something that is already broken".\nProposal\nSet the on-chain max_code_size back to a sane value of 3 MiB. A larger value is not expected to work due to networking restrictions. Related discussions about this are in polkadot/#7108 and polkadot/#7105.\nImpact on Para*s\nParachain/Parathread teams should check that all queued runtime upgrade have a size of at most 3 MiB (the Runtime Size as reported by srtool). A sweep across all parachains showed that the largest is currently 1.7 MiB, that is about 57% of the new limit. So no problem here.\nImpact on Developers\n-',
                                       'like_post': '0', 'dislike_post': '0', 'decision': '8%', 'confirmation': '0%',
                                       'aye': '100.0%', 'nay': '0.0%', 'ayes': '1.8M DOT', 'nays': '0 DOT',
                                       'support': '558.0K DOT', 'issuance': '1.1B DOT', 'comment': []}}]},
                 {'name_them': 'Small Spender', 'links': [
                     {'link': 'https://polkadot.polkassembly.io/referenda/11', 'id': '11', 'name_post': 'propose_spend',
                      'date': 'an hour ago',
                      'data': {'name_author': 'Polkadot_Brasil', 'status': 'Decision Deposit Placed',
                               'model': 'Democracy', 'date_edit': 'an hour ago',
                               'post_text': 'This is a referendumV2 whose proposer address (13oPHqA8Us9duK1tj5ozaUrgt28bRLPE9YAoqV1zCZdWQncH) is shown in on-chain info below. Only this user can edit this description and the title. If you own this account, login and tell us more about your proposal.',
                               'like_post': '0', 'dislike_post': '0', 'decision': '', 'confirmation': '25%',
                               'aye': '0.0%', 'nay': '100.0%', 'ayes': '0 DOT', 'nays': '11 DOT', 'support': '0 DOT',
                               'issuance': '1.1B DOT', 'comment': []}},
                     {'link': 'https://polkadot.polkassembly.io/referenda/10', 'id': '10',
                      'name_post': 'Polkashots.io Cloud Costs January-April 2023', 'date': '12 hours ago',
                      'data': {'name_author': '🏢 MIDL.dev', 'status': 'Deciding', 'model': 'Democracy',
                               'date_edit': '12 hours ago',
                               'post_text': 'Dear Polkadot Community,\nPolkashots.io was the first snapshot service for validators and node operators available since Early 2021. During its time, it provided a valuable service to validators and Parity engineers alike, that ensured reliability of our network.\nThere is a new mechanism, Warp Sync, that makes this service redundant, therefore we stopped making new snapshots in April 2023. We are seeking the reimbursment of Google Cloud expenses for the Jan-Apr period as well as the deposit for the Gov1 Proposal replaced by this. The total is 3,936.69 DOT.\nAll details can be found in the proposal page:\nhttps://hackmd.io/@nicolasochem/B19RK5lmh\nThank you very much for your consideration',
                               'like_post': '0', 'dislike_post': '0', 'decision': '2%', 'confirmation': '0%',
                               'aye': '78.3%', 'nay': '21.7%', 'ayes': '152.3K DOT', 'nays': '42.1K DOT',
                               'support': '107.6K DOT', 'issuance': '1.1B DOT', 'comment': [
                              {'name_comment': '14Do...9B92', 'time_comment': '9 hours ago',
                               'text_comment': '@682874e1f4b94207b11c36290\nfixed, ty', 'like': '0',
                               'dislike': '0'}]}}]}, {'name_them': 'Big Spender', 'links': [
            {'link': 'https://polkadot.polkassembly.io/referenda/8', 'id': '8',
             'name_post': 'Nova Wallet 4th Proposal: Multistaking dashboard, Staking Nomination Pools, Wall...',
             'date': 'a day ago', 'data': {'name_author': '✨👍✨ Day7 ✨👍✨', 'status': 'Deciding', 'model': 'Treasury',
                                           'date_edit': 'a day ago',
                                           'post_text': 'Nova Wallet 4th Proposal: Multistaking dashboard, Staking Nomination Pools, WalletConnect v2, New Assets tab UI, Community Requested Features, Reimbursement for delivered features:\nhttps://docs.google.com/document/d/13SzuZ_sUWnn3AAUJfHn-ld1ww8BGKRagTD8P30pg5tU\n\nFeature set of the proposal (see proposal)\nMultistaking dashboard\nStaking Nomination Pools\nWalletConnect v2\nNew Assets tab UI\nCommunity Requested Features\nReimbursement for delivered features\n\nContext of the proposal:\nNova Wallet is the leading mobile app for the Polkadot and Kusama ecosystem:\n        🌌 70+ Polkadot eco & EVM networks\n        🔀 250+ Cross-chain channels\n        🥞 User-friendly staking: DOT, KSM, GLMR, MOVR, PDEX, AZERO, TUR, CAPS, KMA\n        🙋🏼\u200d♀️ OpenGov, Agile Delegations & Governance v1 support\n        🌐 DApp browser with support for the Polkadot JS & MetaMask protocols\n        🖼 Access to RMRK & Statemine NFTs\n        📱 Hardware wallets support for Parity Signer & Ledger Nano X\n        🚀 Polkadot & Kusama Crowdloans\n        💖 Amazing & User-friendly UX/UI\n        ✨ Community-focused\n        ⚡️ Fast & Feature-rich\n        🦾 Secure & Open source\n        🙆 50 000+ active users on both iOS/Android\n        🎁 Funded by the Polkadot, Kusama, Moonbeam, Moonriver, KILT Treasuries, working with 130+ teams in the eco\n        In December 2022, our previous (3rd) Treasury Proposal was approved, and now by April 2023, we have successfully delivered upon all the proposed features and more. Please refer to Nova Wallet Demo #32 in order to review the features which we have delivered upon:\n        Our goal for Nova Wallet is to build and maintain a high quality, open source, community-focused, and feature rich mobile application, which will have no network biases and can function with no limitations/restrictions.\n        Apart from developing open source Nova Wallet iOS & Android mobile apps, our team is consistently contributing to the Polkadot ecosystem by providing open source SDKs, design assets, knowledge-sharing sessions, and infrastructure. Examples include:\nSubstrate SDKs for iOS and Android development\nNova Utils GitHub — metadata & configs for networks, crowdloans, DApps, cross-chain transfers\nSubQuery API projects developed and hosted by Nova Wallet team\nNova Assets Figma — Polkadot eco tokens, networks, DApps\nHosted metadata portal for Polkadot & Kusama ecosystem networks — metadata portal for Parity Signer, ecosystem hardware wallet\nPolkadot in Action — series of videos & articles focused on onboarding people to help utilize the power of Polkadot & Kusama ecosystem through the Nova Wallet\nDelegate Registry — an open-source repository for Delegates to fill out their information to attract more delegations through the Agile Delegation feature Other apps are using it (besides Nova Wallet): OpenGov Insights\n        This proposal covers the further development of Nova Wallet as a mobile application for the Polkadot & Kusama ecosystems, allowing us to expand upon the already large set of features contained within Nova Wallet by expanding Staking features with Nomination Pool support and Multistaking dashboard, WalletConnect v2 integration, Assets UI upgrade, and fulfilling various requests by the community, further elevating the UX of Nova Wallet.\n\nThe intended outcomes from this proposal:\n6 months implementation of this proposal’s feature set for the Nova Wallet iOS and Android apps (as described in The feature set of the proposal section)\nReimbursement for delivered features\nPublic demos: every 2-4 weeks (see YouTube)\nUpdates to AppStore / Google Play: every 1-4 weeks\nOpen source iOS and Android mobile apps under Apache 2.0 license\nOpen source iOS and Android Substrate SDKs under Apache 2.0 license\n\nPlease review the full proposal with a detailed description & costs: https://docs.google.com/document/d/13SzuZ_sUWnn3AAUJfHn-ld1ww8BGKRagTD8P30pg5tU',
                                           'like_post': '0', 'dislike_post': '0', 'decision': '8%',
                                           'confirmation': '0%', 'aye': '95.2%', 'nay': '4.8%', 'ayes': '1.9M DOT',
                                           'nays': '96.0K DOT', 'support': '556.3K DOT', 'issuance': '1.1B DOT',
                                           'comment': [{'name_comment': '121e...mG7N', 'time_comment': "26th Apr '23",
                                                        'text_comment': 'Hey everyone! ✨ Anton Khvorov here. Our team has decided to proceed with this proposal to Polkadot Treasury. Previously, 2 weeks ago, we have submitted it to Kusama Treasury, and after 2 weeks of discussion made this decision to the multiple factors, including current state of Kusama Treasury, community feedback, and analyzing current funding distribution of Nova Wallet. Will add more details later today to this post.\nBelow you can find the post with proposal scope tracking. Although this proposal is still under the discussions and scope is the subject to be changed based on the community feedback, due to the long queue on Polkadot Treasury (2 months of discussion) we have decided to not stop the development of Nova Wallet as leading mobile application for Polkadot ecosystem, and start proposal execution with low-risk high-value features, such as WalletConnect v2.\nPlease feel free to ask any questions regarding the proposal! Would be happy to address it together with my team.',
                                                        'like': '0', 'dislike': '0'},
                                                       {'name_comment': '121e...mG7N', 'time_comment': "26th Apr '23",
                                                        'text_comment': 'Proposal scope progress tracking:\n✅ DONE:\nWalletConnect v2\n• Add button(s) for WalletConnect v2 to start the QR code scan\n• Show the initialize connection with DApp screens\n• Sign message screens\n🎁 Released on 12.05.23 for Android (link) and on 15.05.23 for iOS (link)\n\nCommunity Requested Features\n• Add Search feature on Referendum (Vote) screen\n• Add a setting to authorize operation with pin code / bio\n• Add filter on Vote screen to display only voted/un-voted/all referendums\n🎁 Released on 24.05.23 for iOS (link) and on 26.05.23 for Android (link)\n\n\n👨🏻\u200d💻IN PROGRESS:\nNew Assets tab UI\n• Add main wallet features on Assets tab\n• Update design of Balance card\n• Send flow from Assets tab\n• Receive flow from Assets tab\n• Topup flow from Assets tab\n• Update UI for Operation history\nMultistaking dashboard\n• Show all staking options with APY\n• Display active staking options on the multistaking dashboard with total stake & total rewards\n• Display “More options” in the end of Multistaking dashboard screen\n\n\n📫 PLANNED:\nStaking Nomination Pools\n• Start staking via Nomination Pool\n• Stop staking in Nomination Pool\n• Display Nomination Pool status\n• Display Nomination Pool alerts\n• Display Total Staking rewards from Nomination Pool staking\n• Stake more tokens in Nomination Pool\n• Unstake tokens from Nomination Pool\n• Show Unstaking progress from Nomination Pool\n• Redeem Unstaked tokens from Nomination Pool\n• Display available rewards\n• Claim available rewards\n• Restake available rewards\nMultistaking dashboard\n• Unify flow for Nominator and Nomination Pool participant depending on staking amount\n• Display onchain staking conditions/terms in oversimplified view upon clicking on one of the available options for Staking\nCommunity Requested Features\n• Show Total Staking rewards for selected time period\n• Show fiat value of transfer/staking reward upon the time it was received',
                                                        'like': '0', 'dislike': '0'},
                                                       {'name_comment': 'bLd Nodes | ChadStakeKing',
                                                        'time_comment': "26th Apr '23",
                                                        'text_comment': 'I think Polkadot is the right place, Nova has been constantly delivering a high quality wallet always fitting new features of Substrate and more. Mobile is the key to mainstream adoption, I want to bring my support to this proposal.',
                                                        'like': '2', 'dislike': '0'},
                                                       {'name_comment': '12WW...L961', 'time_comment': "13th May '23",
                                                        'text_comment': "Nova was on AAG on May 8. Here's the clip (6:52) 👇 https://twitter.com/TheKusamarian/status/1655959229306421293",
                                                        'like': '2', 'dislike': '0'},
                                                       {'name_comment': '121e...mG7N', 'time_comment': 'a day ago',
                                                        'text_comment': 'Greetings everyone! Anton from Nova Wallet here ✨\nAfter more than 2 months in Discussion phase & upgrade to OpenGov on Polkadot, we have submitted our proposal to onchain voting! According to Subscan, 7d MVA for DOT on 16.06.23 is 4.569 USD.\nLink to onchain companion: https://polkadot.polkassembly.io/referenda/8',
                                                        'like': '0', 'dislike': '0'},
                                                       {'name_comment': 'Paradox', 'time_comment': 'a day ago',
                                                        'text_comment': 'Happy to support the Nova team.\nLooking forward to Proxy Support :D',
                                                        'like': '1', 'dislike': '0'},
                                                       {'name_comment': "G' Expect Chaos", 'time_comment': 'a day ago',
                                                        'text_comment': 'I support this proposal because I think Nova is a project with a strong contribution to the democratization of Polkadot. We all know that the majority of web users tend to use mobile devices, and this will continue to accelerate. Nova offers an easy-to-use, comprehensive and visually appealing wallet. 👍\nI look forward to seeing the use of staking nomination pools and the multistaking dashboard.',
                                                        'like': '1', 'dislike': '0'},
                                                       {'name_comment': '13mg...jwBM', 'time_comment': 'a day ago',
                                                        'text_comment': "We need native Mobile version of polkadot.js, no need so many other wallets. Besides, it's Such a big expense.",
                                                        'like': '0', 'dislike': '0'},
                                                       {'name_comment': '', 'time_comment': 'a day ago',
                                                        'text_comment': 'Hope this new grant will get us a lot of great things to use! All for it, great work, team!',
                                                        'like': '1', 'dislike': '0'}]}}]}]

    temp_ivent = [{'data_com': 'Jun 18, 2023', 'time_comm': '12:45 pm', 'author_comm': 'Staking Epoch',
                   'text_comm': 'Start of a new staking session 6707'},
                  {'data_com': 'Jun 18, 2023', 'time_comm': '6:36 pm', 'author_comm': 'Staking Era',
                   'text_comm': 'Start of a new staking era 1112'},
                  {'data_com': 'Jun 19, 2023', 'time_comm': '12:52 am', 'author_comm': 'Start New Council Election',
                   'text_comm': 'Election of new council candidates period 158'},
                  {'data_com': 'Jun 19, 2023', 'time_comm': '11:29 am', 'author_comm': 'Council Motion',
                   'text_comm': 'Council Motion 0x852dee77...'},
                  {'data_com': 'Jun 22, 2023', 'time_comm': '7:46 pm', 'author_comm': 'Council Motion',
                   'text_comm': 'Council Motion 0x59ad6aed...'},
                  {'data_com': 'Jun 26, 2023', 'time_comm': '12:52 am', 'author_comm': 'Start Referendum Voting Period',
                   'text_comm': 'Start of next referendum voting period 39'},
                  {'data_com': 'Jun 29, 2023', 'time_comm': '3:35 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 1, 2023', 'time_comm': '5:52 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute named scheduled task 0x9dc85167...'},
                  {'data_com': 'Jul 4, 2023', 'time_comm': '12:52 am', 'author_comm': 'Start Spend Period',
                   'text_comm': 'Start of next spend period 46'},
                  {'data_com': 'Jul 12, 2023', 'time_comm': '5:53 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 12, 2023', 'time_comm': '5:08 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 13, 2023', 'time_comm': '6:33 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 13, 2023', 'time_comm': '8:52 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 13, 2023', 'time_comm': '9:57 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 13, 2023', 'time_comm': '10:12 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 14, 2023', 'time_comm': '1:35 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 14, 2023', 'time_comm': '3:00 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 14, 2023', 'time_comm': '6:42 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 15, 2023', 'time_comm': '1:13 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Jul 15, 2023', 'time_comm': '11:52 pm', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute anonymous scheduled task'},
                  {'data_com': 'Aug 1, 2023', 'time_comm': '12:52 am', 'author_comm': 'Start Parachain Lease Period',
                   'text_comm': 'Start of the next parachain lease period 13'},
                  {'data_com': 'Aug 1, 2023', 'time_comm': '12:52 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute named scheduled task 0x9a6e9257...'},
                  {'data_com': 'Oct 24, 2023', 'time_comm': '12:52 am', 'author_comm': 'Scheduled Task',
                   'text_comm': 'Execute named scheduled task 0x21fc0d6c...'}]
